# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.6

# compile C with /usr/bin/gcc
C_FLAGS = -O3 -ffast-math -std=gnu99 -I/home/bjmey/arch/dl/ruby/Chipmunk-4.1.0/src  

C_DEFINES = 

